title: Aquí mi blog, aquí un amigo
author: Joan Ginard
email: jginardi@uoc.edu
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  De momento es una cosa de prueba.

# social links
twitter_username: joanginard1
github_username:  JoanGinard

show_excerpts: true # set to false to remove excerpts on the homepage
